@startmindmap package dependencies
legend right
    | Color | Package Type |
    |<back:DarkCyan>          </back>| meta package|
    |<back:red>          </back>| package planed, but not started yet|
    |<back:yellow>          </back>| package started, but not finished|
    |<back:green>          </back>| package finished|
    |<back:lightgreen>          </back>| package used moretimes as dependency |
endlegend

top to bottom direction
*[#green] lomiri-env
*[#DarkCyan] lomiri-base/lomiri-meta
  *[#yellow] lomiri-base/lomiri
    *[#green] dev-libs/qmenumodel
    *[#green] net-libs/geonames
    *[#lightgreen] lomiri-extra/lomiri-app-launch
      *[#lightgreen] dev-util/click
        *[#green] properties-cpp
          *[#green] dev-build/cmake-extras
      *[#green] gnome-extra/zeitgeist
      *[#lightgreen] lomiri-base/lomiri-api
      *[#green] gui-libs/mir::guru
  *[#yellow] lomiri-indicators/lomiri-network-indicator
    *[#lightgreen] lomiri-base/lomiri-api
    *[#red] lomiri-extra/lomiri-url-dispatcher
      *[#lightgreen] dev-util/click
    *[#lightgreen] lomiri-extra/lomiri-app-launch

@endmindmap
